// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlPzNvphAYEchYEip5RY2KfCmKE40R0_U',
    appId: '1:721566148954:web:8e8b07cff048f0edb1eb63',
    messagingSenderId: '721566148954',
    projectId: 'notesapp-d5d3f',
    authDomain: 'notesapp-d5d3f.firebaseapp.com',
    storageBucket: 'notesapp-d5d3f.firebasestorage.app',
    measurementId: 'G-CBMJ517JW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM7b23jJIW98zoX2rL1OTi35jdGN_DHY0',
    appId: '1:721566148954:android:423d0c3f9ebd6680b1eb63',
    messagingSenderId: '721566148954',
    projectId: 'notesapp-d5d3f',
    storageBucket: 'notesapp-d5d3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0gleFhCqROw-rDLC9O64hAwza0F_d3mY',
    appId: '1:721566148954:ios:7a4548bcc551c170b1eb63',
    messagingSenderId: '721566148954',
    projectId: 'notesapp-d5d3f',
    storageBucket: 'notesapp-d5d3f.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0gleFhCqROw-rDLC9O64hAwza0F_d3mY',
    appId: '1:721566148954:ios:7a4548bcc551c170b1eb63',
    messagingSenderId: '721566148954',
    projectId: 'notesapp-d5d3f',
    storageBucket: 'notesapp-d5d3f.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlPzNvphAYEchYEip5RY2KfCmKE40R0_U',
    appId: '1:721566148954:web:5b2f33c83f19824cb1eb63',
    messagingSenderId: '721566148954',
    projectId: 'notesapp-d5d3f',
    authDomain: 'notesapp-d5d3f.firebaseapp.com',
    storageBucket: 'notesapp-d5d3f.firebasestorage.app',
    measurementId: 'G-NCX5JG27F2',
  );
}
